### PR TITLE
Add postgres connection class

### PR DESCRIPTION
**Pull request by tvogels01**
Adds connection and connection test, something like:
```scala
val db = new PostgresConnection(sourceConfiguration.jdbcUrl, getClass.getCanonicalName)
db.withDSLContext(implicit context =>  /* code block */ )
```

@pettyjamesm @triplec1988 Refactoring connection code

### CODE REVIEW

**Comment by triplec1988** [comment]
Looks good to me...what are the implications for using this? Will we need to change any of our imports/code usage?

**Comment by tvogels01** [comment]
We can start refactoring code because we all need to connect to the hyppo database.  For example, this can replace https://github.com/harrystech/hyppo-stripe-integration/blob/master/src/main/scala/com/harrys/sql/util/GrainsConnection.scala

**Comment by triplec1988** [comment]
Ok, cool, that's clear now. Looks good.

**Comment by pettyjamesm** [comment]
Yup, LGTM :shipit:

**Pull request merged**
